### PR TITLE
Update code to use the new client with the new parser

### PR DESCRIPTION
**Pull request by mateuszmlc**
Depends on https://github.com/spacetimehq/spacetime-ts/pull/19

After merging the spacetime-ts PR we need to release new versions for @spacetimexyz/client + @spacetimexyz/react and update dependencies in this project. I have tried it with local overrides and it works, but I would double check after releasing to npm.

The most important change is in `config-overrides.js`:
```diff
 module.exports = function override (config) {
+  config.resolve.alias['@spacetimexyz/client'] = '@spacetimexyz/client/web'
 ...
   config.plugins = (config.plugins || []).concat([
     ...
+    new CopyPlugin({
+      patterns: [
+        {
+          from: 'node_modules/@spacetimexyz/parser/web/*.wasm',
+          to: 'static/js/[name][ext]',
+        },
+      ],
+    }),
   ])
```

Webpack doesn't automatically copy over our .wasm file from node_modules, so we have to edit our website's config to copy it with a plugin. In the future we could look into inlining .wasm files in the bundled javascript.
The alias should be also possible to remove, I was getting a type mismatch error after removing it, but it might've been because my node_modules was "dirty"

### CODE REVIEW

**Comment by calummoore** [comment]
This is failing because its looking for `@spacetimexyz/client` which should now be `@spacetimexyz/client/web`

**Comment by mateuszmlc** [comment]
We need to update client to the new version before this works, I can publish a new version on npm now that it's merged

**Comment by mateuszmlc** [comment]
Done

**Comment by mateuszmlc** [comment]
TODO: Change description back to desc

**Review by calummoore — APPROVED** [review]

**Pull request merged**
